// Configuration file for environment variables
// This file is generated automatically from .env
// Do not edit this file directly - modify .env instead

window.ENV = {
    NEXT_PUBLIC_FORM: "xqargjvr"
};
